"""drop default constraint

Revision ID: 33612bfde906
Revises: 833f6bf8392b
Create Date: 2025-12-15 14:15:13.558284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33612bfde906'
down_revision: Union[str, Sequence[str], None] = '833f6bf8392b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('storages_default_key'), 'storages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('storages_default_key'), 'storages', ['default'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
