"""update_file_state_enum_and_remove_delete_columns

Revision ID: 61c858126ef5
Revises: 5ac5027266d2
Create Date: 2025-12-10 14:10:10.571008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61c858126ef5'
down_revision: Union[str, Sequence[str], None] = '5ac5027266d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE filestate ADD VALUE IF NOT EXISTS 'DELETING'")
    op.execute("ALTER TYPE filestate ADD VALUE IF NOT EXISTS 'UPLOAD_FAILED'")
    op.execute("ALTER TYPE filestate ADD VALUE IF NOT EXISTS 'DELETE_FAILED'")
    
    op.drop_column('files', 'delete_status')
    op.create_unique_constraint(None, 'storages', ['default'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storages', type_='unique')
    op.add_column('files', sa.Column('delete_status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'FAILED', 'COMPLETED', name='deletestatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
