"""replace tools with vector_store_ids

Revision ID: 833f6bf8392b
Revises: 61c858126ef5
Create Date: 2025-12-15 12:00:34.965874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '833f6bf8392b'
down_revision: Union[str, Sequence[str], None] = '61c858126ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vector_store_ids', sa.ARRAY(sa.String(length=64)), nullable=True))
    op.drop_column('users', 'tools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('users', 'vector_store_ids')
    # ### end Alembic commands ###
