"""add bot and s3 bucket to storage

Revision ID: fdc7013d9a25
Revises: 42b23aba7562
Create Date: 2026-01-17 20:06:53.022521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc7013d9a25'
down_revision: Union[str, Sequence[str], None] = '42b23aba7562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storages', sa.Column('bot_name', sa.String(), nullable=True))
    op.add_column('storages', sa.Column('bot_id', sa.String(), nullable=True))
    op.add_column('storages', sa.Column('s3_bucket', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'storages', ['bot_id'])
    op.create_unique_constraint(None, 'storages', ['s3_bucket'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storages', type_='unique')
    op.drop_constraint(None, 'storages', type_='unique')
    op.drop_column('storages', 's3_bucket')
    op.drop_column('storages', 'bot_id')
    op.drop_column('storages', 'bot_name')
    # ### end Alembic commands ###
